### PR TITLE
Ubuntu import 1.0-rc93

### PR DESCRIPTION
**Pull request by lucaskanashiro**
Version 1.0.0~rc93 contains an important fix for this bug:

https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1916485

I uploaded the package to this PPA:

https://launchpad.net/~lucaskanashiro/+archive/ubuntu/docker-20.10/+packages

As you can see it FTBFS on armhf, there is an integer overflow in the test of the fix we want. I filed an upstream bug here:

https://github.com/opencontainers/runc/issues/2846

I considered to skip this test for now, but since the failing test is seccomp related, which we want to make sure it is working, I turned it down. Let me know if you have a better approach for this issue.

FWIW autopkgtest is still happy on amd64:

```
autopkgtest [17:10:37]: @@@@@@@@@@@@@@@@@@@@ summary
basic-smoke          PASS
command1             PASS
```

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
Weird, it does not FTBFS on armhf in Debian:

https://buildd.debian.org/status/fetch.php?pkg=runc&arch=armhf&ver=1.0.0%7Erc93%2Bds1-2&stamp=1612785406&raw=0

**Comment by tianon** [comment]
Looks like Debian backported https://github.com/opencontainers/runc/pull/2768 in https://salsa.debian.org/go-team/packages/runc/-/blob/9738f0204be7776e862cdce695b1c2b9d60109c1/debian/patches/0008-fix-patchpbf-test-on-32-bit.patch :eyes:

**Comment by tianon** [comment]
(otherwise this looks very benign to me, assuming it works with containerd and Docker :+1:)

**Comment by lucaskanashiro** [comment]
Thanks @tianon . I backported the same patch and it fixed the issue. I do not know why I did not see this patch before :facepalm: 

I am testing everything using the PPA in the description (there you can find docker.io and containerd packages as well), I am going to wait for your +1 to move forward.

**Review by tianon — APPROVED** [review]
:+1:

**Comment by lucaskanashiro** [comment]
Thanks! I am just waiting for the FFe approval to get it merged and uploaded.

**Comment by lucaskanashiro** [comment]
FFe was approved.

**Pull request merged**
